### ISSUE TITLE
Should we call _makeRPCCall with await?

### ISSUE THREAD

**Issue by xiaoch05** [simolus3/web3dart#24]
https://github.com/simolus3/web3dart/blob/a0968df6745214601409e49a261711b778b3e027/lib/src/web3client.dart#L184

function sendRawTransaction call _makeRPCCall without **await**, and then cannot catch the exception thrown by _makeRPCCall. The exception can't be transfered to the caller.

**Comment by simolus3** [comment]
Sorry, can you please clarify the issue?
Currently, when there's an error in `_makeRPCCall`, the `sendRawTransaction` call will throw the same error (see [here](https://api.dartlang.org/stable/2.1.0/dart-async/Future/then.html)
>If onError is not given, and this future completes with an error, the error is forwarded directly to the returned future.

Thus, the caller of `sendRawTransaction` will receive the error. I think this is alright because this library is not responsible for any IO error and we should inform the caller when something went wrong.
We could achieve the same behavior with `await`, but I don't really see a benefit when we're just returning one `Future` mapped with `then`, the code won't become substantially more simple.

**Comment by xiaoch05** [comment]
Yea, it works. Thanks:)
