### ISSUE TITLE
Using decimal for EtherAmount.

### ISSUE THREAD

**Issue by modulovalue** [simolus3/web3dart#58]
Have you considered using [decimal](https://pub.dev/packages/decimal) instead of BigInt for the implementation of EtherAmount?

**Comment by simolus3** [comment]
This could be used to make some apis nicer without giving up on precision, thanks. I'll take a look at it.

There could still be some cases where an amount can't be represented exactly (e.g. 1/3 Ether). We would have to throw in those cases, rounding is not really an option.

**Comment by modulovalue** [comment]
Decimal is based on [rational](https://pub.dev/packages/rational) and should be able to handle infinite precision.

**Comment by simolus3** [comment]
Sorry, should have been more clear. The smallest unit that can be sent with Ethereum is 10⁻¹⁸ Ether. If we allowed users to send a rational amount (say exactly 1/3 Ether), we would still have to convert that to a multiple of 10⁻¹⁸. We can get pretty close because the unit is so small, but we wouldn't be able to send that amount exactly.

It works really way the other way, though: For an `EtherAmount` received, we can expose that as a decimal to make working with it easier for users.

**Comment by modulovalue** [comment]
Thank you for the clarification, I completely forgot about that part.
